### ISSUE TITLE
Add a compiler for Grammarkdown

### ISSUE THREAD

**Issue by arhadthedev** [arhadthedev/fecer-browser#3]
## As-is

There are plans to add a support for a JavaScript binding of ECMAScript. To supply it, two parts will be implemented: a runtime+a standard library, and a compiler+an optimizer.

For a compiler, we need to convert Grammarkdown description of an ECMAScript into a parser, couple with logic for specification-defined semantics, and cover everything with an interface.

## Issues

Even though a generator for a parser is a standalone project, we first need to define all features required for Fecer Browser specifically. So this issue is created and updated for such features until the generator satisfies all needs for Fecer Browser 1.0.

## To-be

A proposed layout of a grammar binding file:

```yaml
goal_symbols:
  # 5.1.4 The Syntactic Grammar <https://tc39.es/ecma262/#sec-syntactic-grammar>
  lexical:
    - InputElementDiv
    - InputElementTemplateTail
    - InputElementRegExp
    - InputElementRegExpOrTemplateTail
    - Pattern
  syntactic:
    - Script
    - Module
```

## Extra materials

First, implements ECMA-262 as in https://ci.tc39.es/preview/tc39/ecma262/sha/ddef0ffe544f006f8d2efae745059b72d7f35c01/ and link to this specific version from a documentation, manual included. Then, apply all changes from tc39/ecma262 up to `master`.
