### ISSUE TITLE
Use an YAML serialization for script bytecode

### ISSUE THREAD

**Issue by arhadthedev** [arhadthedev/fecer-browser#5]
Bytecode of LLVM and Java are expressed via special assembly languages. Bytecode of Dutyblasm (a script runtime of Fecer Browser) needs to be expressed via YAML instead.

Here is a content of an example file, `abi_lowlevel_module.yaml`:

```yaml
globals:
  main: "125677"
  somehex: "\x16\x12\x15"
  someint: 1563335
  somereal: 1.256e128

blocks:
  dosomething:
    captures:
      globals:
        glob1: main
        glob2: somehex
        glob3: someint563_335
      caller_operations:
        main: {in1: fooz, in2: ret}
    exit_branching:
      condition: bar
      for_true: baz
      for_false: baaz
    operations:
      foo: add in1, in2
      baz: or input_100, glob12
      baaz: bitor input_100, globl3

exports:
  mytype: 0
```

Such way has the following advantages:

- Explicit removal of ordering for blocks and "variables"; think in dependencies, not in command order that does not matter because of an optimizer.

- Explicit removal of number ids where unnecessary; think in abstractions; for disassembly, ids can be generated as a part of names.

- See bytecode as plain data that describes dependencies between transformations, not as some special thing like sequential commands to a virtual processor.

- Use existing serialization format; no need in a specialized parser, no need to learn new grammar.

- Availability of already existing YAML processing tools; no need to reinvent an infrastructure.

- Limited expressive tools lead to a natural separation of unrelated data because marrying them in such an environment is a struggle; we already separated instructions and their domain of values into separate files because of clutter.

Now, about the domain. For optimization, we need to have an explicit list of all possible values that any "variable" can take for any callee of a block. If we continue to use YAML, we can convert bytecode modules into domain definitions using a command line tool.

For example, `another_module.yaml > dutyblasm-domaindef`may give the following:

```yaml
dosomethingelse:
  glob1:
    any_caller: 125677
  glob2:
    any_caller: "\x16\x12\x15"
  glob3:
    any_caller: 1563335
  in2:
    main:
      - [1, 100]
      - foo[^n]
      - boo: baz
  foo:
    main:
      - [1, 100]
      - "[^n]
      - boo:
        - baz
        - 169
        - bar: hello
```
